### ISSUE TITLE
Is it used only for the Admin app?

### ISSUE THREAD

**Issue by gustavklopp** [WoLpH/django-tags-input#11]
I don't see how to use it in my views.
It actually creates some additional tables (of the type 'taggedentry_tag' if I tagging the table 'taggedentry' with tag from table 'tag'), but then what do I need to do?
Thanks!

**Comment by WoLpH** [comment]
The field functions as a regular many to many fields which always creates an intermediate table in django. Instead of the admin fields and widgets you can use the regular fields and widgets to use in normal views:

- https://django-tags-input.readthedocs.io/en/latest/tags_input.fields.html#tags_input.fields.TagsInputField
- https://django-tags-input.readthedocs.io/en/latest/tags_input.widgets.html#tags_input.widgets.TagsInputWidget

To make the javascript part make sure to include the form media in your templates before the form widgets: https://docs.djangoproject.com/en/1.11/topics/forms/media/

**Comment by gustavklopp** [comment]
this is how I did this:
MyExample/myapp/forms.py
```python
from tags_input import fields, widgets
from myapp.models import *
from django import forms

class ItemstobetaggedForm(forms.ModelForm):
    ...
    itemtobetaggedtags = fields.TagsInputField( Words.objects.all(),
                                    create_missing=True,
                                    required=False)

    class Meta:
        model = Itemstobetagged
        fields = (...,'itemtobetaggedtags')
        widget= {
            'itemtobetaggedtags': widgets.TagsInputWidget # getting the tags fo the texts (using Django tagsinput app)
}
```

in MyExample/urls.py
```python
from django.conf.urls import url,include

urlpatterns = [
    ...
    url(r'^tags_input/', include('tags_input.urls', namespace='tags_input')), # used for tagging    
]
```

then implementing it in views and template:
MyExample/myapp/views.py
```python
def itemstobetagged_create{request):
    if request.method == 'POST': # the form has been posted
            f = ItemstobetaggedForm(request.POST)
            if f.is_valid():
                  f.save()
    else:
        f = Itemstobetagged()        
    return render(request,'myapp/itemstobetagged_create.html',{'form':f })
```

and the template: MyExample/myapp/static/myapp/itemstobetagged_create.html
```html
{% load staticfiles %}
{% load staticfiles %}
{% load i18n %} {# used for internationalization #}
<link rel="stylesheet" type="text/css" href="{% static "lwt/css/jquery.tagsinput.css" %}">

<form action="{% url 'itemstobetagged_create'%}>
{% csrf_token %}
<table>
	...
        <tr>
	<td>The Tags:</td>
	<td>{# adding tags for the Terms thanks to Django-tags-input app #}{{ form.wordtags }} 
	</td>
	</tr>
	<tr>
        ....
	<input type="submit" name="create" value="Create New Itemstobetagged" />
	</tr>
</table>
</form>
```

What do you think?

**Comment by WoLpH** [comment]
First of all... apologies for the slow response, I've got too much on my mind right now ;)
Second, That looks good but I don't think there's any need for overriding the widget as well as the field in the form. When overriding the field the widget should be overridden as well.

I'll try to test your demo as soon as possible and if everything works properly I'll add it to the example project and the docs.
