### ISSUE TITLE
xoxco/jQuery-Tags-Input seems discontinued. How about using underovsky/jquery-tagsinput-revisited?

### ISSUE THREAD

**Issue by gustavklopp** [WoLpH/django-tags-input#12]
Sadly xoxco/jQuery-Tags-Input project seems discontinued: 
No new update since 2 years,  74 issues opened without message from the maintainer.
And indeed the version of JQuery inside django-tags-input is a 5 year ago version.

There's some fork still continueing (issues are adressed, recent): https://github.com/underovsky/jquery-tagsinput-revisited/issues
Besides there are some useful options like new delimiters when creating tags for example.

Would it be possible to update the JQuery inside django-tags-input?

**Comment by WoLpH** [comment]
I've updated the develop branch with the revisited tags input and the latest jquery(-ui). Can you verify that everything is working OK for you?

**Comment by WoLpH** [comment]
The new release is online, thanks for all the help!
