### ISSUE TITLE
TagsInputMixin and models with multiple manyToMany fields

### ISSUE THREAD

**Issue by gb119** [WoLpH/django-tags-input#13]
The TagsInputMixin doesn't like cases where a model has more than one ManyToMany fields, but not all of them are for tagging. 

I could offer a pull request which adds a get_tag_fields() method that returns a list of fm2m fields that are to be used for tagging (or None for the default behavious of all tags). The default behaviour of this method is to look for a tag_fields attribute which should be an iterable containing the names of fields to be tagged. formfield_for_manytomany() then does a call to the parent method if tag_fields is defined and doesn't contain the current field - this allows one to specify in the ModelAdmin class which m2m fields should be tag fields.

**Comment by WoLpH** [comment]
That would be a nice solution for the problem :)
If you're willing to create a pull request I'm all for it!

Thanks for the help

**Comment by WoLpH** [comment]
The new release is online, thanks for all the help!
