### ISSUE TITLE
Widget doesn't display properly with Django 2.0.2, Python 3.6.5

### ISSUE THREAD

**Issue by Nyrio** [WoLpH/django-tags-input#16]
Hi,

I'm working with Python 3.6.5, Django 2.0.2, and it might be useful to say that for my forms I'm also using django-bootstrap-form.

I need this widget because for a project I want to be able to add tags for items and I want people to be able to search items matching a list of tags.

I have followed all installation steps. In `settings.py` I have the mapping:
```
TAGS_INPUT_MAPPINGS = {
    'myProject.Tag': {
        'field': 'name',
        'create_missing': True,
    },
}
```

Then my `Item` model has a field:
```
tags = models.ManyToManyField(Tag, blank=True,
         related_name="items",
         verbose_name='Tags', help_text='Missing tags will be auto-created')
```

I have a form based on this model:
```
class CreateItemForm(forms.ModelForm):
    tags = fields.TagsInputField( Tag.objects.all(),
                                  create_missing=True,
                                  required=False)
    class Meta:
        model = Item
        fields = [..., "tags"]
        widgets = {
            "tags": widgets.TagsInputWidget
        }
```

And of course a view and a template but they are pretty straightforward and will not help understanding the problem.

When I test the form, I begin to write but there is not suggestion, no tag is displayed as such after a comma, it's just like I'm editing a simple text input field. On the following example there should be a list of all tags beginning with a, but there isn't:
![image](https://user-images.githubusercontent.com/17441062/38589932-bd4157f6-3d36-11e8-95d8-8f6df3a2fe92.png)

If I add the tags separated by a comma, everything's done well in my database, though. So it is just display problems.

I thought it could come from the fact that I'm using bootstrap forms, but I have the same problem on the admin interface which doesn't use it.

If the problem is on my use of the widget, any idea how I can solve that? And if it's really an issue... well, I hope you'll be able to find its origin and solve it.

Thanks.

**Comment by WoLpH** [comment]
In this case I actually think the template might be the most important part :)
Specifically, the `form.media` part: 
https://github.com/WoLpH/django-tags-input/blob/f09559d1ef0d2a79f5ad86c6066d935c4fdb14e4/example/templates/index.html#L6-L10

Depending on whether you have jQuery already loaded you'll also need this in your `settings.py`:
```python
TAGS_INPUT_INCLUDE_JQUERY = True
```

**Comment by Nyrio** [comment]
Thanks for your reply.
I've used [Django Ajax Selects](https://django-ajax-selects.readthedocs.io/en/latest/index.html) instead, but you're probably right about the template problems, my code was missing the `{{ form.media }} `.
