### ISSUE TITLE
widget render method needs mandatory renderer argument for 2.1

### ISSUE THREAD

**Issue by gb119** [WoLpH/django-tags-input#17]
tags input is breaking on Django 2.1 as the widget's render method lacks a renderer keyword parameter. Just adding renderer=None in line 31 in widgets.py does the trick and will work for Django 1.11 on wards (whether this is the canonically correct solution is another question....)

**Comment by WoLpH** [comment]
It's fixed and I've pushed a new release which supports Django 2.1 as well :)
