### ISSUE TITLE
Static files not properly included in PyPi pacakge?

### ISSUE THREAD

**Issue by gb119** [WoLpH/django-tags-input#18]
Installing from pypi with pip seemed to not set the static files correctly, but I'm not familiar enough with how the javascript should be deployed to work out why its wrong...

**Comment by WoLpH** [comment]
Just a quick sanity check, did you run the `django-admin collectstatic` command? :)

It's quite possible that there is a bug, but I'd like to make sure before I try to hunt this down.

**Comment by WoLpH** [comment]
Thanks for the help, I noticed that the manifest file was indeed incorrect
