### ISSUE TITLE
Tags Input 

### ISSUE THREAD

**Issue by Allwingit** [WoLpH/django-tags-input#19]
Hi Team,

 I have tried to Django-tags-input package in my project. I couldn't get result as shown in the below image (Screen Shot taken from Read me document of this same repository).
![screen shot 2018-10-28 at 8 55 53 pm](https://user-images.githubusercontent.com/34136858/47618024-14c30280-daf4-11e8-8146-1c126e88c837.png)
 I am getting following error in my terminal window while testing this package.
![screen shot 2018-10-28 at 8 51 59 pm](https://user-images.githubusercontent.com/34136858/47618030-3e7c2980-daf4-11e8-8fc1-ca8e51c18f13.png)
Can you please help me on this ?

**Comment by WoLpH** [comment]
You're missing the static files so I'm guessing you need to run the [collectstatic](https://docs.djangoproject.com/en/2.1/ref/contrib/staticfiles/#collectstatic) command :)

```
django-admin collectstatic
```

**Comment by Allwingit** [comment]
Thanks for your quick response. I tried it with your suggested method. Still I am getting the same result.
![screen shot 2018-10-29 at 9 44 50 pm](https://user-images.githubusercontent.com/34136858/47663891-e6acf380-dbc3-11e8-86fa-9ca8d54db0c2.png)
From console error message, I tried to find those .css and .js file in the staticfiles directory. But there is no such folder present inside it.
![screen shot 2018-10-29 at 9 45 38 pm](https://user-images.githubusercontent.com/34136858/47663957-0cd29380-dbc4-11e8-9110-14822e9783fd.png)

Can you help me solve this ?

**Comment by WoLpH** [comment]
It seems it's a silly mistake on my end... while testing I was using bower to build the dist files so I still had them and the jquery-tagsinput-revisited-2.0 library has a .gitignore automatically ignoring the dist files. So... it was not included in the package :(

I've created a new release which solves the issue. If you install it with `pip install -U django-tags-input` and run the collectstatic after, it should work :)

**Comment by Allwingit** [comment]
Yes. I will try. :) . Thank you.

**Comment by Allwingit** [comment]
Hi,
 I am using python 3.6 . I have created a virtual environment for python 3.
 Then I clone this repository to that directory. After activate virtualenv, I installed Django and Django-tags-input (as you mentioned pip install -U Django-tags-input).
 Then as mentioned in the readme.md, I moved to the example directory and try to run python manage.py collectstatic. I am getting below error.

![screen shot 2018-10-29 at 11 38 48 pm](https://user-images.githubusercontent.com/34136858/47670696-d0a72f00-dbd3-11e8-9e47-f1ea41fb6c98.png)

Let me know, if I miss anything.

**Comment by WoLpH** [comment]
The code expects the path to the example project to be in your `sys.path`. One way to fulfill that need is to do: `export PYTHONPATH=..` (parent directory) in this case.

If you're running the example project from the git checkout of this library installing using `pip install -e .` on the git checkout is probably the easiest solution.

**Comment by Allwingit** [comment]
Ya. I will check that. 

I am trying to integrate tags_input with my project. I followed the steps mentioned in the readme document.

1. Installed Django-tags-input (pip install -U django-tags-input )
2. Added in the INSTALLED_APPS ('tags_input')
3. URL is mapped.(url(r'^tags_input/', include('tags_input.urls', namespace='tags_input')),)
4. Tagging input field is mapped.  
(
TAGS_INPUT_MAPPINGS = {
    'someapp.model': {'field': 'testtag' (Character field), 'create_missing': True},
}
) 
I tried it with ForgineKey field. But It doesn't make any difference.

5. I ran collectstatic.
6. Run the server.

I am getting response like, it works like a normal character field. Not like a tag input field.
In tags_input package installed, there is no static folder available. Hence when I ran collect static, there is no static files related to tags_input. 

Is it expected? what am I missing in the integration?

**Comment by WoLpH** [comment]
The static folder configuration is a Django thing, which probably isn't needed for the "runserver" command but which you'll need anyhow for deployment so that's good to setup in any case :)
Here's the howto for that section: https://docs.djangoproject.com/en/2.1/howto/static-files/

The `example` error you showed earlier is something that should be specific to the example project, that should never happen when you're trying to integrate it within your own project unless you're including the `example` app as well.

How are you running the server? With `DEBUG=True` and using `runserver`? Or are you using something like Gunicorn/uwsgi

**Comment by Allwingit** [comment]
Ya. Using runserver and debug as TRUE.

Issue 1:
I am testing the tags-input package separately and I am facing that example module not found issue.
During integration, I didn't include those package.

Issue 2:
In my project, I separately install Django-tags-input using pip. There , I am not getting proper tags-input.

**Comment by WoLpH** [comment]
It seems there were still some strange things happening with the packaging of the static files. I've completely refactored it and uploaded a new release (and tested it in a clean vm to be certain it properly works everywhere).

That seems to fix the issue for me, can you verify it works for you as well?

**Comment by Allwingit** [comment]
Hi,

Thank you for the solution. Kindly find my observation.

Issue 1:
   Static files are copied properly. But still It doesn't seems like tags_input. Still package has some minor issues.

Issue 2:
  I followed the steps mentioned in the quick test on package. No module found issue is solved. But still tag input got an issue. Find the attached screen shot for the same.
 
![screenshot 2018-10-31 at 9 47 05 pm](https://user-images.githubusercontent.com/34136858/47802699-e1cc7900-dd56-11e8-985c-3bbd036c1952.png)

![screenshot 2018-10-31 at 9 50 55 pm](https://user-images.githubusercontent.com/34136858/47802806-1f310680-dd57-11e8-883c-64eab85dee00.png)

Kindly do the needful.

**Comment by Allwingit** [comment]
It seems, .css name should be changed to jquery-tagsinput-revisited-2.0.min.css , instead of jquery.tagsinput-revisited-2.0.min.css.

**Comment by Allwingit** [comment]
I manually renamed and verified it works fine. It would be helpful, if it is changed with this package. :)

**Comment by WoLpH** [comment]
I'm sorry for all the issues :(

A lot of silly mistakes due to sleep deprivation I suppose. I've created another (hopefully final) release

**Comment by Allwingit** [comment]
Can you please help me on integration part. 

I have created a model with character field and I want it to be act like tag_input field.

Kindly find the below procedure I followed:
 1. created virtualenv 
 2. Installed Django-tags-input (pip install -U django-tags-input) 
 3. Created models with required fields.
 4. Added tags_input in Installed_App.
 5. Mapped that character field in TAG_INPUT_MAPPING 
 TAGS_INPUT_MAPPINGS = {
    'questionbank.Questions': {'field': 'testtag', 'create_missing': True},
   }
6. added url path in url.py. 
    url(r'^tags_input/', include('tags_input.urls', namespace='tags_input')),

7. run collectstatic .(For production purpose)


Is there anything I missed? I didn't get proper tags_input field here.

**Comment by WoLpH** [comment]
Assuming you want it to work within the admin, your admin model will need to inherit the [`TagsInputAdmin`](https://github.com/WoLpH/django-tags-input/blob/master/tags_input/admin.py#L61-L62)

Or if you're working outside of the admin, you'll have to use the [`TagsInputField`](https://github.com/WoLpH/django-tags-input/blob/master/tags_input/fields.py#L9-L67)

**Comment by Allwingit** [comment]
Yes it looks good now.. Need to install latest package and check it again..

**Comment by Allwingit** [comment]
Have you come across this print statement ?
  nin fields None tag
 
I am seeing it often in my logs.

**Comment by Allwingit** [comment]
Thank you for your great support.
Valuable input from your side helped me integrate it with my project. Everything seems to be working. 

👍

**Comment by WoLpH** [comment]
That was a leftover debug print statement, I've removed it from the build now :)
