### ISSUE TITLE
Documentation build is broken

### ISSUE THREAD

**Issue by gordonzola** [WoLpH/django-tags-input#21]
Hi. I’m noticing that the link to the documentation hosted on ReadTheDocs is broken (404 error). Browsing the project on RTD shows that the last builds are failed, like this one: https://readthedocs.org/projects/django-tags-input/builds/9078934/

I suspect there is a problem in the build command configured on RTD, since I managed to build the docs locally without errors.

Can you check the RTD configuration, and put the docs back online? Thanks.

**Comment by WoLpH** [comment]
There was a big in RTD causing the builds to fail some time ago. I completely forgot to try later, but it should be good again
