### ISSUE TITLE
Wrong tox envs on Travis

### ISSUE THREAD

**Issue by gordonzola** [WoLpH/django-tags-input#22]
The build badge on the project shows errors: travis is unable to build the envs `py35-django20` and `py36-django20`, because those envs does not exist (anymore, probably) in the `tox.ini` file.

The `.travis.yaml` should be fixed to use the correct envs and supported versions.

Also, the `README.rst` tells that the only supported Django versions are < 2.0, which seems false given #15 and the `tox.ini` envs. Is Django-2.2 officially supported?

Thanks

**Comment by WoLpH** [comment]
True, I bumped a bit of the project to support newer versions but I haven't changed everything it seems.

While it's not officially tested anymore, any Django version 1.4 and up should work
