### ISSUE TITLE
Tag auto-complete not working on edit

### ISSUE THREAD

**Issue by PittCaleb** [WoLpH/django-tags-input#24]
I am using a tag for labels and it works perfect on creating a new article.

When I edit the same article, it shows a comma separated list, and adding new works, but the existing tags are not boxed as seen on create and new ones are neither auto-completed nor provide feedback as with add.

Receiving the following error on console:
Uncaught TypeError: $(...).tagsInput is not a function

Any thoughts?

**Comment by WoLpH** [comment]
That means the javascript is not loaded somehow. Do you have anything customized in the admin? Different form class, templates, etc?

Also, which version of Django? :)

**Comment by PittCaleb** [comment]
Django 2.1.5

Working that some JS isn't loading or loading early enough, attempted to add it in the admin class:

```
class KBArticleAdmin(tags_input_admin.TagsInputAdmin, NonSortableParentAdmin, ArticleAdminMixin):
    model = KnowledgeBase

    class Media:
        css = {"all": ("css/kbarticle.css",)}
        widgets = {
            'snippet': Textarea,
            'tags': tags_input.fields
        }

```
Tried with widgets and then fields without success.  Any thoughts greatly appreciated.  Tags for this model are in the ArticleAdminMixin which is still a model.ModelAdmin type not TagsInputAdmin.  Tried switching that too without success.

**Comment by WoLpH** [comment]
Your custom `Media` class might be causing this :)
If that's the case, that's easy enough to remedy though, simply inherit the `Media` class for the `AdminTagsInputWidget` and you're done.

https://github.com/WoLpH/django-tags-input/blob/master/tags_input/widgets.py#L105-L127

In your case:
```python
from tags_input.widgets import AdminTagsInputWidget

class KBArticleAdmin(tags_input_admin.TagsInputAdmin, NonSortableParentAdmin, ArticleAdminMixin):
    model = KnowledgeBase

    class Media(AdminTagsInputWidget.Media):
        css = {"all": ("css/kbarticle.css",) + AdminTagsInputWidget.Media.css['all']}
        widgets = {
            'snippet': Textarea,
            'tags': tags_input.fields
        }
```

I'm not a 100% certain that will fix it, but it should :)

**Comment by PittCaleb** [comment]
Appreciate your quick responses today.  Made above changes without success.  Same issue.  Works fine on add, nothing on edit.  Changed .fields to .widgets and tried without entirely for the widgets setting:

```
class KBArticleAdmin(tags_input_admin.TagsInputAdmin, NonSortableParentAdmin, ArticleAdminMixin):
    model = KnowledgeBase

    class Media(AdminTagsInputWidget.Media):
        css = {"all": ("css/kbarticle.css",) + AdminTagsInputWidget.Media.css['all']}
        widgets = {
            'snippet': Textarea,
            'tags': tags_input.widgets
        }
```

**Comment by WoLpH** [comment]
I'm not sure what's causing it but my guess is that it's something to do with one of your other admin mods. Just to make sure I've run the demo app and tested with Django 2.1 without any issues.

I would suggest looking at the other admin mods to see if they modify the edit template somehow.
