### ISSUE TITLE
ImportError: cannot import name 'curry' from 'django.utils.functional' 

### ISSUE THREAD

**Issue by itakesmallbytes** [WoLpH/django-tags-input#25]
Hello,

I'm a bit newer to Django and am getting this error while using Django 3.0. Is there a workaround you suggest for this? 

Thank you so much!

**Comment by WoLpH** [comment]
I've created a new release that supports Django 3.0 :)

**Comment by itakesmallbytes** [comment]
Yay!! You are the best! Hope all is well on your end, cheers!

Sent from my iPhone
—
Daisy Almaguer
P: 806-282-3554

On May 6, 2020, at 5:46 PM, Rick van Hattem <notifications@github.com>
wrote:

﻿

I've created a new release that supports Django 3.0 :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/WoLpH/django-tags-input/issues/25#issuecomment-624908335>,
or unsubscribe
