### ISSUE TITLE
$(...).tagsInput is not a function

### ISSUE THREAD

**Issue by gmlwo530** [WoLpH/django-tags-input#26]
Python version : 3.7.6
Django version : 2.2
Browser : Chrome
django-tags-input version : 5.0.0

I got below error

```
jquery.js:3827 Uncaught TypeError: $(...).tagsInput is not a function
    at HTMLDocument.<anonymous> ((index):1805)
    at mightThrow (jquery.js:3534)
    at process (jquery.js:3602)
```

And my admin code

```python
class FooTag(tags_input_admin.TagsInputAdmin):
    form = FooTagForm
    tag_fields = ["tags"]


class FooAdmin(ImportExportModelAdmin, FooTag):
....
```

Is it problem of `django-tags-input`?

**Comment by WoLpH** [comment]
That means the javascript isn't loaded. I'm guessing it's related to the custom form.

Normally the widget should be able to provide the needed javascript through the `Media` class: https://github.com/WoLpH/django-tags-input/blob/95ec1bcd0d840af15b603a9b00650749e3754bbf/tags_input/widgets.py#L103-L124

In any case, you can also manually add the `Media` to your form or template of course

**Comment by good-lancer** [comment]
I think you didn't load form.media.
please insert following code before "{{ form.as_p }}".

> {{ form.media }}

**Comment by gmlwo530** [comment]
Sorry, i forgot this issue.

Looking at the code in more detail, i found a problem.

It is related to the custom form that @WoLpH 's comment

I wrote down my admin code in more detail.

```python
# models.py

class Tag(models.Model):
     ...

class FooParent(models.Model):
     ...

class Foo(models.Model):
    foo_parent = models.ForeignKey(FooParent)
    tags = models.ManyToManyField(Tag)



# forms.py

class FooAdminForm(forms.ModelForm):
    foo_parent = forms.ModelChoiceField(
        queryset=FooParent.objects.all(),
        widget=autocomplete.ModelSelect2(url='select2_fk_foo_parent')  # I think this line override media property of 'AdminTagsInputWidget'  
    )

    class Meta:
        model = Foo
        fields = ('foo_parent')



# admin.py

...

class FooTag(tags_input_admin.TagsInputAdmin):
    form = FooTagForm
    tag_fields = ["tags"]

class FooAdmin(ImportExportModelAdmin, FooTag):
    form = FooAdminForm
    ....


```

I used [django-autocomplete-light](https://github.com/yourlabs/django-autocomplete-light/) in my admin. I think [this line](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_select2/widgets.py#L83)(Select2WidgetMixin is superclass of autocomplete.ModelSelect2) override media property of 'AdminTagsInputWidget'.

Actually when i delete below code in `FooAdminForm`, tags field is work.

Is there any way to use both `django-tags-input` and `django-autocomplete-light` in `FooAdmin`?

**Comment by WoLpH** [comment]
@gmlwo530 Django should handle the merging of the media files automatically, so my guess is that the javascript files are conflicting instead.

One workaround could be to include the media for this library before (or after, it depends) the other one and see if that fixes it.
I would suggest trying something like this:
```python
from tags_input import widgets


class FooAdminForm(forms.ModelForm):
    foo_parent = forms.ModelChoiceField(
        queryset=FooParent.objects.all(),
        widget=autocomplete.ModelSelect2(url='select2_fk_foo_parent')  # I think this line override media property of 'AdminTagsInputWidget'
    )

    class Meta:
        model = Foo
        fields = ('foo_parent')


    class Media(widgets.AdminTagsInputWidget.Media):
        pass
````

**Comment by gmlwo530** [comment]
I tried to put `class Media(widgets.AdminTagsInputWidget.Media):` before and after [django-autocomplete-light](https://github.com/yourlabs/django-autocomplete-light/) library. It's not work same javascript error.

+ I found issue of [django-autocomplete-light](https://github.com/yourlabs/django-autocomplete-light/) similarly this issue.
From that issue, maintainer suggest making [django-autocomplete-light](https://github.com/yourlabs/django-autocomplete-light/) not to use jquery.

Should i have to resolve this issue on Javascript level?

**Comment by WoLpH** [comment]
There might be a "dirty" fix for this issue. Manually adding the `jquery.tagsinput-revisited-2.0.min.js` to your template after all other media includes. My guess is that even with the earlier attempts we're still not overriding the Django media import order.

**Comment by gmlwo530** [comment]
Ok, i solved this. Although i don't like this code, i have to do other feature in this project. If you have code better than this code, comment please.

```python
class FooAdminForm(forms.ModelForm):
    foo_parent = forms.ModelChoiceField(
        queryset=FooParent.objects.all(),
        widget=autocomplete.ModelSelect2(url='select2_fk_foo_parent')  # I think this line override media property of 'AdminTagsInputWidget'  
    )

    class Meta:
        model = Foo
        fields = ('foo_parent')

    @property
    def media(self):
        import copy
        media = super(FooAdminForm, self).media
        sorted_media_js = copy.copy(media._js)
        # Below code to change javascript file order
        sorted_media_js.remove('jquery.tagsinput-revisited-2.0.min.js')
        sorted_media_js.remove('jquery-3.2.1.min.js')  # If this file isn't deleted, js error is occured. I did not found a reason.
        sorted_media_js.append('jquery.tagsinput-revisited-2.0.min.js')
        return forms.Media(
            css=media._css,
            js=tuple(sorted_media_js)
        )
```

@WoLpH If only you are okay, I will close this issue

**Comment by WoLpH** [comment]
That's roughly as expected I guess. The problem lies within including multiple jquery libraries which conflict with each other.

Glad to see you've found a workaround.
