### ISSUE TITLE
Cannot overwrite field queryset from view.

### ISSUE THREAD

**Issue by Marchamp** [WoLpH/django-tags-input#27]
Thanks you for your awesome project.

I am unable to overwrite TagsInputField queryset from the view. How may I proceed? Thanks.
forms.py:
```
class SomeForm(forms.ModelForm):
   some_field=TagsInputField(queryset=SomeModel.objects.none(),create_missing=False)
```

views.py
```
def view_function(request):
   form=SomeForm(request.POST or None)
   form.fields['some_field'].queryset=SomeModel.objects.filter(......)
    ......
```

**Comment by WoLpH** [comment]
It needs an extra step because it's not only the field that uses the queryset, but the widget as well.

```
def view_function(request):
    form=SomeForm(request.POST or None)

    # Slightly convoluted, but this should work:
    some_field = form.fields['some_field']
    some_field.queryset=SomeModel.objects.filter(......)
    some_field.mapping = None
    some_field.widget.mapping = some_field.get_mapping()
```

**Comment by Marchamp** [comment]
> It needs an extra step because it's not only the field that uses the queryset, but the widget as well.
> 
> ```
> def view_function(request):
>     form=SomeForm(request.POST or None)
> 
>     # Slightly convoluted, but this should work:
>     some_field = form.fields['some_field']
>     some_field.queryset=SomeModel.objects.filter(......)
>     some_field.mapping = None
>     some_field.widget.mapping = some_field.get_mapping()
> ```

I tried it. The field still displays all SomeModel instances despite the filter.
I have done this:
```
qs=SomeModel.objects.filter(......)
print(qs)
some_field=form.fields['some_field']
some_field.queryset=qs
some_field.mapping=None
print(some_field.get_mapping())
some_field.widget.mapping=some_field.get_mapping()
print(some_field.widget.mapping)
```
`somefield.get_mapping()` and `some_field.widget.mapping` both print out the same dictionary but the form in the template still displays all SomeModel instances.

Thanks.

**Comment by WoLpH** [comment]
Oops... you're right. The actual autocomplete results are generated by the autocomplete view here: https://github.com/WoLpH/django-tags-input/blob/master/tags_input/views.py

So your options are:
1. change the mapping configuration in your settings to add specific filters
2. change the view to return different results for your query

**Comment by Marchamp** [comment]
Thanks for your help. I ended up using your widget for models that do not have ForeignKeys.
