### ISSUE TITLE
how to change placeholder?

### ISSUE THREAD

**Issue by DreH-World** [WoLpH/django-tags-input#28]

**Comment by good-lancer** [comment]
I am tried to change "add a tag" to "search for a tag"
but I couldn't change the placeholder

**Comment by WoLpH** [comment]
There's no pretty way to do it currently, but you can easily do it by modifying the template: https://github.com/WoLpH/django-tags-input/blob/master/tags_input/templates/tags_input_widget.html

To edit the text you need to modify the `defaultText` parameter to `tagsInput`: http://jsfiddle.net/7j0sgokf/

So if you modify any line between 6 and 20 of the `tags_input_widget.html` to include that, you're done.
