### ISSUE TITLE
Problem with collecstatic with Whitenose

### ISSUE THREAD

**Issue by mihasK** [WoLpH/django-tags-input#29]
During collectstatic:

whitenoise.storage.MissingFileError: The file '"images/ui-icons_555555_256x240.png"' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x102b1a3a0>

The issues seems like lies in the comment of https://github.com/WoLpH/django-tags-input/blob/master/tags_input/static/jquery-ui-1.12.1.min.css .
If you remove comment all works fine

**Comment by WoLpH** [comment]
I do think this is actually a bug in whitenoise, but I don't see any issue with merging this.

I'll create a new release soon :)

**Comment by WoLpH** [comment]
I've created a new release with your fix

Thank you for the help!
