### ISSUE TITLE
Show verbose_name and help_text in tag input field

### ISSUE THREAD

**Issue by zakgreene** [WoLpH/django-tags-input#8]
I'd love to implement this style of tags input into my admin interface, but it's fairly important the verbose_name and help_text show up on those fields. Neither seem to work. I commented out tags_input from INSTALLED_APPS, and the default Django ManyToMany field showed them.

**Comment by WoLpH** [comment]
It seems you're right. It looks like the Django help text behaviour changed in 1.8 so I'll have to fix that. Stay tuned :)

**Comment by WoLpH** [comment]
The new release (Version 3.0.0) has full Django 1.8 and higher support with help texts as well

**Comment by zakgreene** [comment]
Thanks for the fix, but for some reason when I upgraded and tried to open the admin panel I got an error, "TemplateDoesNotExist: tags_input_widget.html." Oddly enough I do see tags_input_widget.html in site_packages/tags_input. Any ideas?

**Comment by WoLpH** [comment]
In that case your `TEMPLATES` setting is probably missing the `APP_DIRS` flag. It should be something like this:

```

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            # ... some options here ...
        },
    },
]
```

**Comment by zakgreene** [comment]
Ah, I actually forgot to comment it back in under `INSTALLED_APPS`, sorry about that.

`help_text` seems to work, but not `verbose_name`. Any way to get that in?

**Comment by zakgreene** [comment]
Also, any way to make it work in a StackedInline?

**Comment by WoLpH** [comment]
I'll have a look :)

**Comment by WoLpH** [comment]
Both work in the latest release (3.1.0)  :)

And the demo project shows an example configuration for a StackedInline.

**Comment by zakgreene** [comment]
This is awesome, thanks a bunch!
